"use client";
import PageTitle from "@/components/PageTitle";
import { useDemoCRM } from "@/components/DemoCRMProvider";
import { createBrowserSupabaseClient } from "@/lib/supabase-browser";
import { FormEvent, useEffect, useState } from "react";
const KEY='ludhiana-ad-service-crm-settings';
type Data={business:string;warning:number;red:number;assignment:'round_robin'|'least_active'|'manual';timezone:string};
export default function Settings(){
  const {mode}=useDemoCRM();const [saved,setSaved]=useState(false);const [notice,setNotice]=useState('');const [orgId,setOrgId]=useState('');const [data,setData]=useState<Data>({business:'Demo Business',warning:30,red:120,assignment:'round_robin',timezone:'Asia/Kolkata'});
  useEffect(()=>{async function load(){if(mode==='demo'){try{const v=localStorage.getItem(KEY);if(v)setData(JSON.parse(v))}catch{}return;}const supabase=createBrowserSupabaseClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:profile}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(!profile?.organization_id)return;setOrgId(profile.organization_id);const {data:org,error}=await supabase.from('organizations').select('name,warning_minutes,red_alert_minutes,assignment_rule,timezone').eq('id',profile.organization_id).single();if(error){setNotice(error.message);return;}if(org)setData({business:org.name,warning:Number(org.warning_minutes||30),red:Number(org.red_alert_minutes||120),assignment:(org.assignment_rule||'round_robin') as Data['assignment'],timezone:org.timezone||'Asia/Kolkata'});}void load()},[mode]);
  async function submit(e:FormEvent){e.preventDefault();setNotice('');if(data.red<data.warning){setNotice('Red alert time must be greater than or equal to the warning time.');return;}if(mode==='demo'){localStorage.setItem(KEY,JSON.stringify(data));setSaved(true);setTimeout(()=>setSaved(false),2000);return;}const supabase=createBrowserSupabaseClient();if(!supabase||!orgId){setNotice('Workspace is not ready.');return;}const {error}=await supabase.from('organizations').update({name:data.business,warning_minutes:data.warning,red_alert_minutes:data.red,assignment_rule:data.assignment,timezone:data.timezone}).eq('id',orgId);if(error){setNotice(error.message);return;}setSaved(true);setTimeout(()=>setSaved(false),2000)}
  return <><PageTitle title="CRM Settings" subtitle="Company profile, lead rules and response-time discipline."/>{saved&&<div className="notice" style={{marginBottom:12}}>{mode==='live'?'Settings saved to your CRM.':'Settings saved in this demo browser.'}</div>}{notice&&<div className="notice danger" style={{marginBottom:12}}>{notice}</div>}<form onSubmit={submit}><div className="grid-2"><div className="card"><div className="card-head"><h3>Business profile</h3></div><div className="card-body form"><label>Business name<input className="input" value={data.business} onChange={e=>setData({...data,business:e.target.value})}/></label><label>Timezone<select className="select" value={data.timezone} onChange={e=>setData({...data,timezone:e.target.value})}><option value="Asia/Kolkata">Asia/Kolkata (IST)</option><option value="UTC">UTC</option></select></label><button className="btn btn-primary">Save Changes</button></div></div><div className="card"><div className="card-head"><h3>Lead discipline rules</h3></div><div className="card-body form"><label>Warning if untouched after<select className="select" value={data.warning} onChange={e=>setData({...data,warning:Number(e.target.value)})}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour</option></select></label><label>Red alert after<select className="select" value={data.red} onChange={e=>setData({...data,red:Number(e.target.value)})}><option value={60}>1 hour</option><option value={120}>2 hours</option><option value={240}>4 hours</option></select></label><label>Default assignment<select className="select" value={data.assignment} onChange={e=>setData({...data,assignment:e.target.value as Data['assignment']})}><option value="round_robin">Round Robin</option><option value="least_active">Least Active Leads</option><option value="manual">Manual</option></select></label><button className="btn">Update Rules</button></div></div></div></form></>;
}
