import Link from "next/link";
import { BellRing, Bot, ChartNoAxesCombined, ContactRound, MessageCircleMore, Route, ShieldCheck, UsersRound, Zap } from "lucide-react";

const features = [
  [ContactRound,"Meta Lead Capture","Bring Facebook and Instagram lead-form enquiries into one clean workspace."],
  [BellRing,"Follow-up Reminders","Schedule next actions, highlight overdue leads, and reduce missed follow-ups."],
  [MessageCircleMore,"WhatsApp Workspace","Connect the official WhatsApp Business Platform and work from a shared inbox."],
  [Route,"Sales Pipeline","Move leads from New to Contacted, Interested, Follow-up, Converted or Lost."],
  [UsersRound,"Team Assignment","Route incoming enquiries to agents and track ownership, response and conversion."],
  [ChartNoAxesCombined,"Ad-to-Sale Reporting","See which campaigns generate enquiries and which enquiries become customers."],
  [Zap,"Silence Alerts","Flag untouched leads when response-time thresholds are crossed."],
  [Bot,"Automation Ready","Built for templates, routing rules, reminders and future AI-assisted workflows."],
  [ShieldCheck,"Multi-Tenant SaaS","Each customer company gets isolated CRM data while you retain Super Admin control."],
] as const;

export default function Home() {
  return <>
    <div className="container">
      <nav className="nav"><Link className="brand" href="/"><span className="logo">L</span>Ludhiana Ad Service CRM</Link><div className="navlinks"><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></div><div className="nav-actions"><Link className="btn" href="/login">Login</Link><Link className="btn btn-primary" href="/signup">Start Free Trial</Link></div></nav>
      <section className="hero"><div><span className="eyebrow"><Zap size={14}/> Built for Facebook & Instagram advertisers</span><h1><span className="gradient-text">Turn Ad Leads</span><br/>Into Customers.</h1><p>Stop losing enquiries inside spreadsheets and scattered WhatsApp chats. Capture leads, assign agents, schedule follow-ups and keep your sales team accountable from one CRM.</p><div className="hero-actions"><Link className="btn btn-primary" href="/signup">Start Free Trial</Link><Link className="btn" href="/dashboard">Open Live Demo</Link></div><div className="small-note">No card required • Demo CRM works instantly • Upgrade when your team grows</div></div>
      <div className="mock"><div className="mock-top"><span className="dot"/><span className="dot"/><span className="dot"/><span style={{marginLeft:10,fontSize:11,color:'#7588a0'}}>ludhiana-ad-service-crm.vercel.app/dashboard</span></div><div className="mock-body"><div className="mini-row"><div className="mini-card"><span>New Leads</span><strong>24</strong></div><div className="mini-card"><span>Follow-ups</span><strong>11</strong></div><div className="mini-card"><span>Converted</span><strong>8</strong></div></div><div className="leadlist"><div className="leadrow"><strong>Rahul Sharma</strong><span>Insurance Ad</span><span className="pill">New • 8m</span></div><div className="leadrow"><strong>Simran Kaur</strong><span>Salon Offer</span><span className="pill">Interested</span></div><div className="leadrow"><strong>Arjun Mehta</strong><span>Property Leads</span><span style={{color:'#ff8295'}}>Overdue • 2h</span></div><div className="leadrow"><strong>Mehak Arora</strong><span>Instagram</span><span className="pill">Follow-up</span></div></div></div></div></section>
    </div>
    <section id="features" className="section"><div className="container"><div className="section-head"><span className="eyebrow">Everything after the ad click</span><h2>One system for every lead, reply and follow-up.</h2><p>Designed for clinics, salons, insurance teams, agencies, education, real estate and other businesses that depend on Meta Ads enquiries.</p></div><div className="features">{features.map(([Icon,title,text])=><div className="feature" key={title as string}><div className="feature-icon"><Icon size={20}/></div><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></div></section>
    <section id="how" className="section"><div className="container"><div className="section-head"><span className="eyebrow">Simple workflow</span><h2>From Meta lead to closed customer.</h2></div><div className="steps"><div className="step"><span className="num">1</span><h3>Lead arrives</h3><p className="small-note">Facebook, Instagram, website or WhatsApp.</p></div><div className="step"><span className="num">2</span><h3>Assign & contact</h3><p className="small-note">Owner is set and response timer starts.</p></div><div className="step"><span className="num">3</span><h3>Follow up</h3><p className="small-note">Schedule reminders and track overdue actions.</p></div><div className="step"><span className="num">4</span><h3>Convert & report</h3><p className="small-note">Track revenue back to campaign and creative.</p></div></div></div></section>
    <section id="pricing" className="section"><div className="container"><div className="section-head"><span className="eyebrow">Start free</span><h2>CRM included with your advertising service.</h2><p>Keep a free plan for ad clients and monetize advanced automation, team seats and WhatsApp workflows later.</p></div><div className="pricing"><div className="price"><h3>Ads Client Free</h3><div className="amount">₹0 <small>/ month</small></div><ul className="checks"><li>Up to 2 users</li><li>Lead pipeline</li><li>Reminders & notes</li><li>Basic reports</li><li>WhatsApp quick open</li></ul><Link className="btn" href="/signup">Start Free</Link></div><div className="price popular"><span className="eyebrow">Most useful</span><h3>Growth</h3><div className="amount">₹999 <small>/ month</small></div><ul className="checks"><li>5 team users</li><li>Official WhatsApp inbox</li><li>Auto assignment</li><li>Silence alerts</li><li>Campaign conversion reports</li></ul><Link className="btn btn-primary" href="/signup">Start Trial</Link></div><div className="price"><h3>Pro</h3><div className="amount">₹1,999 <small>/ month</small></div><ul className="checks"><li>10 team users</li><li>Advanced automations</li><li>Multiple pipelines</li><li>Priority support</li><li>API / webhook access</li></ul><Link className="btn" href="/signup">Start Trial</Link></div></div></div></section>
    <footer className="footer"><div className="container footer-inner"><span>© 2026 Ludhiana Ad Service CRM. All rights reserved.</span><span><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link> · Built for businesses that grow with Meta Ads.</span></div></footer>
  </>;
}
