"use client";
import PageTitle from "@/components/PageTitle";
import { useDemoCRM } from "@/components/DemoCRMProvider";
import { team as seed } from "@/lib/demo";
import { createBrowserSupabaseClient } from "@/lib/supabase-browser";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Person={id?:string;name:string;role:string;initials:string;leads:number;contacted:number;won:number};
export default function Team(){
  const {mode}=useDemoCRM();const [people,setPeople]=useState<Person[]>(mode==='demo'?seed:[]);const [invite,setInvite]=useState(false);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(mode==='live');
  async function load(){if(mode!=='live')return;const supabase=createBrowserSupabaseClient();if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('profiles').select('id,full_name,role').order('created_at',{ascending:true});if(error){setNotice(error.message);setLoading(false);return;}const {data:leadRows}=await supabase.from('leads').select('assigned_to,status');setPeople((data||[]).map((p:any)=>{const name=p.full_name||'Team member';const owned=(leadRows||[]).filter((l:any)=>l.assigned_to===p.id);return{id:p.id,name,role:String(p.role||'agent').replace(/^./,x=>x.toUpperCase()),initials:name.split(' ').map((x:string)=>x[0]).join('').slice(0,2).toUpperCase(),leads:owned.length,contacted:owned.filter((l:any)=>l.status!=='new').length,won:owned.filter((l:any)=>l.status==='converted').length}}));setLoading(false)}
  useEffect(()=>{void load()},[mode]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name'));const role=String(f.get('role'));const email=String(f.get('email')||'');
    if(mode==='demo'){setPeople([...people,{name,role,initials:name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(),leads:0,contacted:0,won:0}]);setInvite(false);setNotice('Demo team member added.');return;}
    const r=await fetch('/api/team/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:name,email,role:role==='Sales Manager'?'manager':'agent'})});const data=await r.json();if(!r.ok){setNotice(data.error||'Invitation failed.');return;}setInvite(false);setNotice(`Invitation sent to ${email}. The member will appear after accepting the invite.`);
  }
  return <><PageTitle title="Team & Assignment" subtitle="Track ownership, response discipline and conversions by sales agent." action={<button className="btn btn-primary" onClick={()=>setInvite(v=>!v)}>+ Invite User</button>}/>{notice&&<div className="notice" style={{marginBottom:12}}>{notice}</div>}{loading&&<div className="notice" style={{marginBottom:12}}>Loading team…</div>}{invite&&<form className="card card-body" onSubmit={submit} style={{marginBottom:14}}><div className="form-row"><label>Name<input className="input" name="name" required placeholder="Team member name"/></label><label>Email<input className="input" name="email" type="email" required={mode==='live'} placeholder="agent@business.com"/></label></div><label>Role<select className="select" name="role"><option>Sales Agent</option><option>Sales Manager</option></select></label><button className="btn btn-primary">{mode==='live'?'Send Invitation':'Add Demo User'}</button></form>}<div className="team-grid">{people.map((p,i)=><div className="person" key={p.id||`${p.name}-${i}`}><span className="avatar" style={{width:44,height:44}}>{p.initials}</span><h4>{p.name}</h4><p>{p.role} • Active</p><div className="person-stats"><div><strong>{p.leads}</strong>Leads</div><div><strong>{p.contacted}</strong>Contacted</div><div><strong>{p.won}</strong>Won</div></div></div>)}</div><div className="card" style={{marginTop:14}}><div className="card-head"><h3>Auto assignment rule</h3><span className="connected">Configured</span></div><div className="card-body"><p className="small-note">New Meta leads can be distributed Round Robin between active sales agents after the Meta lead ingestion connection is activated. Managers can manually reassign leads.</p><Link className="btn" href="/dashboard/settings">Manage Assignment Rule</Link></div></div></>;
}
