"use client";
import PageTitle from "@/components/PageTitle";
import { useDemoCRM } from "@/components/DemoCRMProvider";
import Link from "next/link";

export default function Dashboard(){
  const {leads,mode,loading,error}=useDemoCRM();
  const converted=leads.filter(l=>l.status==="Converted").length;
  const uncontacted=leads.filter(l=>l.status==="New").length;
  const followups=leads.filter(l=>l.status==="Follow-up"||l.nextFollowUp.toLowerCase().includes("today")).length;
  const pipeline=leads.filter(l=>l.status!=="Lost").reduce((sum,l)=>sum+l.value,0);
  const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(6-i));return d;});
  const counts=days.map(d=>leads.filter(l=>{const x=new Date(l.createdAt);return !Number.isNaN(x.getTime())&&x.toDateString()===d.toDateString()}).length);
  const max=Math.max(1,...counts);
  const attention=[...leads].filter(l=>l.status!=="Converted"&&l.status!=="Lost").sort((a,b)=>(b.waiting.includes('hr')?1:0)-(a.waiting.includes('hr')?1:0)).slice(0,4);
  return <><PageTitle title={`Good evening, ${mode==="demo"?"Demo Business":"Your Business"} 👋`} subtitle="Here is what is happening with your ad leads today." action={<Link href="/dashboard/leads" className="btn btn-primary">+ Add Lead</Link>}/>
  {error&&<div className="notice danger" style={{marginBottom:12}}>{error}</div>}{loading&&<div className="notice" style={{marginBottom:12}}>Loading your CRM workspace…</div>}<div className="stats"><div className="stat"><div className="stat-label"><span>{mode==="demo"?"Total Demo Leads":"Total Leads"}</span><span>↗</span></div><div className="stat-value">{leads.length}</div><div className="delta">{mode==="demo"?"Interactive demo data":"Live CRM database"}</div></div><div className="stat"><div className="stat-label"><span>Uncontacted</span><span>🔴</span></div><div className="stat-value">{uncontacted}</div><div className="delta danger">Follow up fast to reduce leakage</div></div><div className="stat"><div className="stat-label"><span>Follow-ups</span><span>⏰</span></div><div className="stat-value">{followups}</div><div className="delta">Scheduled / pending</div></div><div className="stat"><div className="stat-label"><span>Conversions</span><span>✓</span></div><div className="stat-value">{converted}</div><div className="delta">₹{pipeline.toLocaleString('en-IN')} active pipeline</div></div></div>
  <div className="grid-2"><div className="card"><div className="card-head"><h3>Lead volume — last 7 days</h3><span className="small-note">All lead sources</span></div><div className="card-body"><div className="bars">{counts.map((count,i)=><div key={days[i].toISOString()} className="bar" style={{height:`${Math.max(8,Math.round(count/max*100))}%`}} title={`${count} leads`}><span>{days[i].toLocaleDateString('en-IN',{weekday:'short'})}</span></div>)}</div></div></div><div className="card"><div className="card-head"><h3>Needs attention</h3><Link href="/dashboard/follow-ups" className="small-note">View all</Link></div><div className="card-body">{attention.map(l=><div className="task" key={l.id}><span className="avatar">{l.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div className="task-meta"><strong>{l.name}</strong><span>Waiting {l.waiting} • {l.campaign}</span></div><span className={l.waiting.includes('hr')?'danger':'small-note'}>{l.waiting.includes('hr')?'Overdue':'Open'}</span></div>)}{attention.length===0&&<div className="empty-state">No leads need attention.</div>}</div></div></div>
  <div className="card" style={{marginTop:14}}><div className="card-head"><h3>Latest leads</h3><Link href="/dashboard/leads" className="small-note">Open lead manager</Link></div><div className="table-wrap" style={{border:0,borderRadius:0}}><table><thead><tr><th>Lead</th><th>Campaign</th><th>Owner</th><th>Status</th><th>Next follow-up</th></tr></thead><tbody>{leads.slice(0,5).map(l=><tr key={l.id}><td><strong>{l.name}</strong><br/><span className="small-note">{l.phone}</span></td><td>{l.campaign}</td><td>{l.owner}</td><td><span className={`status ${l.status.toLowerCase().replace('-','')}`}>{l.status}</span></td><td>{l.nextFollowUp}</td></tr>)}</tbody></table></div></div></>;
}
